Added Json reader project
BohdanKalep/carlos-qa-education pull request #10
Opened 2023-09-01 16:17 UTC by CarlosGuadamuz0

2023-09-01 16:46 UTC, BohdanKalep requested changes

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/movie/analizer/MovieAnalyzer.java
> +            String json = readFile("src/main/java/json_homework/files/movies.json"); // Replace with your file path
Path need to be stored into constant string

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/movie/analizer/MovieAnalyzer.java
> +        } catch (IOException | EmptyJsonException e) {
+ as long it is 2 different excceptions:
Empty file and IO it is better to create 2 catches blocks and add a proper logger message:
e.g  JsonReader.logger.error(" file not found" + e.getMessage());
JsonReader.logger.error(" file is empty" + e.getMessage());

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +    public static final Logger logger = LogManager.getRootLogger();
It is better to create an extra folder and class. eg: helper -> LoggerHelper.class and add there logger instance so it can be reused

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/movie/Movie.java
> +    String title;
you can make fields private

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/movie/rating/Rating.java
> +    double rating;
you can make field private

2023-09-01 16:46 UTC, BohdanKalep commented on src/main/java/json_homework/movie/analizer/MovieAnalyzer.java
> +            return movieRatings;
please add loger error message in case of null pointer exception

2023-09-04 20:25 UTC, CarlosGuadamuz0 commented
Hi ! Can you check the changes?

2023-09-04 21:53 UTC, BohdanKalep approved these changes

2023-09-04 23:28 UTC, merged