Pet Store Api Testing
BohdanKalep/carlos-qa-education pull request #12
Opened 2023-09-13 12:41 UTC by CarlosGuadamuz0

2023-09-13 17:11 UTC, BohdanKalep requested changes

2023-09-13 17:11 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +import com.google.gson.*;
Update import

2023-09-13 17:11 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +    public static String convertJsonObjectToUrlEncoded(JsonObject jsonObject) {
Don't use url encoder to encode json body

2023-09-13 17:11 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +            JsonArray testDataObject = JsonParser.parseReader(dataReader).getAsJsonObject()
Where is catch block?

2023-09-13 17:11 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +    public static JsonObject[] readTestDataAndBuild(String testDataFile, String templateFile, String templateName, String testDataKey) throws IOException {
Do not throws exception if you handle it in the method

2023-09-13 17:11 UTC, BohdanKalep commented on src/main/java/json_homework/json_reader/JsonReader.java
> +
Where is catch block?

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/api_constants/ApiTestConstants.java
> +    public static final int SC_NOT_FOUND = 404;
Apache is providing you this status codes. You don't need to create them

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/api_constants/ApiTestConstants.java
> +    public static final String BASE_PATH = "src/test/java/";
Create PathHandler and store there everything related to path

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/PetstoreConstants.java
> +    public static final String BASE_URL = "https://petstore.swagger.io/v2";
Make it a URL builder and keep here everything related to url creation

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +import static api_constants.ApiTestConstants.*;
Remove wildcards

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +    private static final String PET_ENDPOINT = StringUtils.join(BASE_URL, ADD_UPDATE_PET_URL);
Make tests independent from each other

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +        String id = updateByIdData.get("petId").getAsString();
Move work with json, urls and path to other place

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +                .statusCode(200)
Replace with constatns

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/constants/PetConstants.java
> +    public static final String VALID_UPLOAD_IMAGE_BY_ID_DATA = "validUploadImageByIdData"; // Updated
Divide into sections request/response/test data

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/pet/data/PetApiData.java
> +        JsonObject[] findPetData = readTestDataAndBuild(PET_BODY_TEST_DATA, PET_BODY_TEMPLATE, VALID_DELETE_PET_TEMPLATE, VALID_DELETE_PET_TEST_DATA);
You can avoid creating a findPetData variable

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/store/constants/storeApiDataTest.json
> +      "order": "/2147473647"
reuse oreder with %s

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/java/petstore/store/constants/storeApiDataTest.json
> +      "id": 2147473648,
get Id from the response and work with it

2023-09-13 17:11 UTC, BohdanKalep commented on src/test/resources/testng.xml
> +            </class>
You can close tag like this \> instead writing  </class>

2023-09-18 17:48 UTC, BohdanKalep requested changes
UserApiData/ PetApiData / StoreApiData
they used a lot of repetative String initialisations.
It would be better to create a DTO. A class with all necessary fileds, status,id,name and after call this clas and use a setter to set a proper name. In this case you will not need to create the same variables in each method with different values

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/api_constants/ApiTestConstants.java
> +
Remove extra lines in this class

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/constants/PetStoreConstantsConfig.properties
> +paths.petBodyTestData=src/test/java/petstore/pet/constants/petApiDataTest.json
Please keep paths for files and urls separate

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +
Please remove extra lines here

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +
Please remove extra lines here

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +        JsonObject responseBody = createPetResponse.jsonPath().getObject("", JsonObject.class);
Use StringUtils.EMPTY instead of ""

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +                String.format(PET_ID_URL, responseBody.get("id").getAsString()));
as long as you repeating id several times create a constant

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +                        String.format(PET_ID_URL, responseBody.get("id").getAsString()));
create a constatnt for id

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +        String id = createPet.jsonPath().getString("id");
constant for id

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +
Please remove extra lines here

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/store/data/StoreApiData.java
> +        int numberOfDataPoints = new Random().nextInt(2) + 2;
Avoid usage of magic numbers create a variable and put in the variable name purpuse of the value

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/store/data/StoreApiData.java
> +        int numberOfDataPoints = new Random().nextInt(7) + 1; // Generate a random number between 1 and 7
Avoid usage of magic numbers create a variable and put in the variable name purpuse of the value

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/store/data/StoreApiData.java
> +        String petId = String.valueOf(new Random().nextInt(100) + 1);
Avoid usage of magic numbers create a variable and put in the variable name purpuse of the value

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/store/data/StoreApiData.java
> +        String petId = String.valueOf(new Random().nextInt(100) + 1);
Avoid usage of magic numbers create a variable and put in the variable name purpuse of the value

2023-09-18 17:48 UTC, BohdanKalep commented on src/test/java/petstore/user/data/UserApiData.java
> +        int numberOfDataPoints = new Random().nextInt(2) + 2;
You you same randomizer for user and for the pet. Maybe you can create a general method with parameters to use it in all necessary places.

2023-09-19 15:48 UTC, BohdanKalep commented on src/test/java/petstore/pet/data/PetApiData.java
> +        category.addProperty("id", DEFAULT_ID);
change string values for constans

2023-09-19 15:49 UTC, BohdanKalep commented on src/test/java/petstore/pet/data/PetApiData.java
> +        newPet.addProperty("name", generateRandomString());
change string values for constans

2023-09-19 15:49 UTC, BohdanKalep commented on src/test/java/petstore/pet/data/PetApiData.java
> +        newPet.add("photoUrls", generateRandomPhotoUrls());
change string values for constans

2023-09-19 15:49 UTC, BohdanKalep commented on src/test/java/petstore/store/StoreApiTest.java
> +        return responseBody.get("id").getAsString();
change id string values for constans

2023-09-19 15:50 UTC, BohdanKalep commented on src/test/java/petstore/user/data/UserDTO.java
> +public class UserDTO implements Serializable {
Can you explain why do you need Serializable interface here?

2023-09-19 15:50 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +        String status = updateByIdData.get("status").getAsString();
change string values for constans

2023-09-19 15:51 UTC, BohdanKalep commented on src/test/java/petstore/pet/PetApiTest.java
> +        String status = updateByIdData.get("status").getAsString();
change string values for constans

2023-09-19 17:38 UTC, BohdanKalep commented on pom.xml
> +                <artifactId>allure-junit4</artifactId>
You wanted to use allure with this homework as well? Or pushed it accidently?
Make sure you use dependence for testNg as long as you use this framework and not junit

2023-09-19 18:49 UTC, CarlosGuadamuz0 commented on pom.xml
> +                <artifactId>allure-junit4</artifactId>
Sorry it was an error

2023-09-19 21:27 UTC, BohdanKalep approved these changes

2023-09-19 23:05 UTC, merged